In [2]:
# import the required libraries
import pandas as pd

data = pd.read_csv('C:\\Users\\anshul\\PycharmProjects\\scikit-learn\\Datasets\\DTML_Master.csv')

In [3]:
data.head(10)

,CAL_DATE,VNDR_ID,ITEM_NO,LOC,SR_FLAG,CRFA_C,CRFA_R,CRFA_F,CRFA_A,EOQ,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,2017-11-06,AD98,A22-72740-000,13,N,S,9,1,2,1,...,4,0.333,0,2,196,1,-75.00,10.8333,0,0
1,2018-04-24,AD98,A22-69882-000,34,N,S,9,1,2,0,...,5,0.000,0,7,107,9,800.00,4.3333,0,0
2,2018-05-07,DN 4,DN EPG150230,65,N,S,9,1,2,1,...,2,0.000,0,13,178,3,50.00,2.0000,0,0
3,2017-10-18,Z582,04-31885-200,65,N,S,9,1,2,1,...,2,0.000,0,12,166,5,0.00,2.5000,0,0
4,2017-12-06,T606,12-20828-000,34,Y,S,9,1,2,5,...,3,0.000,0,2,108,77,6.94,73.0000,15996,118
5,2018-02-19,JK65,A05-19332-000,65,N,S,9,1,2,1,...,2,0.000,0,12,160,17,-58.53,47.8333,0,261
6,2018-04-16,ASC3,A18-64616-318,1,N,S,9,1,2,1,...,10,0.000,1,11,27,56,-27.27,58.1666,2919,547
7,2017-06-21,ASC3,A18-69613-203,1,N,S,9,1,2,1,...,11,0.250,1,11,1,45,36.36,54.6666,7481,274
8,2017-11-13,B682,A12-28714-000,34,N,S,9,1,2,1,...,0,0.000,0,7,110,4,100.00,3.3333,335,0
9,2017-05-24,PYI,A22-69379-002,1,N,S,9,4,2,1,...,1,0.000,0,15,24,0,0.00,0.0000,0,0

In [4]:
# split the data into feature matrix (X) and response vector (y)
X = data.drop('SR_FLAG', axis='columns')
y = data['SR_FLAG']

In [31]:
X.head()
y.head()

0    N
1    N
2    N
3    N
4    Y
Name: SR_FLAG, dtype: object

In [5]:
import numpy as np

# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)

In [6]:
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

['CAL_DATE', 'VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG', 'FULFILLMENT_RATE_2WKAVG']

<b>Fixing 'FULFILLMENT_RATE_2WKAVG'</b>

In [7]:
X['FULFILLMENT_RATE_2WKAVG'].head()

0    (null)
1    (null)
2         1
3    (null)
4     0.666
Name: FULFILLMENT_RATE_2WKAVG, dtype: object

In [36]:
# identify the unique/distinct set of values for 'FULFILLMENT_RATE_2WKAVG'
# X.groupby('FULFILLMENT_RATE_2WKAVG').nunique()
# len(X['FULFILLMENT_RATE_2WKAVG'].unique()) -- 1002
# 'FULFILLMENT_RATE_2WKAVG' contains deciman numbers along with a null.
# eliminating the nulls from a copy of X
'''
X_mod = X
X_nonnum = X_mod.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)
# modify 'FULFILLMENT_RATE_2WKAVG' to replace NULLS with zeros
X_mod['FULFILLMENT_RATE_2WKAVG'].fillna(0.0, inplace=True)
# checin the non numeric columns again
X_nnumcols = list(X_nonnum)
print(X_nnumcols)
['CAL_DATE', 'VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG', 'FULFILLMENT_RATE_2WKAVG']
X_mod['FULFILLMENT_RATE_2WKAVG'] = X_mod['FULFILLMENT_RATE_2WKAVG'].str.replace('\(0\)', '0')
X_mod['FULFILLMENT_RATE_2WKAVG'].unique()
array(['(0.000)', '1', '0.666', ..., '0.779', '0.856', '0'], dtype=object)
array(['0', '1', '0.666', ..., '0.879', '0.779', '0.856'], dtype=object)
'''

"\nX_mod = X\nX_nonnum = X_mod.select_dtypes(exclude=np.number)\nX_nnumcols = list(X_nonnum)\nprint(X_nnumcols)\n# modify 'FULFILLMENT_RATE_2WKAVG' to replace NULLS with zeros\nX_mod['FULFILLMENT_RATE_2WKAVG'].fillna(0.0, inplace=True)\n# checin the non numeric columns again\nX_nnumcols = list(X_nonnum)\nprint(X_nnumcols)\n['CAL_DATE', 'VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG', 'FULFILLMENT_RATE_2WKAVG']\nX_mod['FULFILLMENT_RATE_2WKAVG'] = X_mod['FULFILLMENT_RATE_2WKAVG'].str.replace('\\(0\\)', '0')\nX_mod['FULFILLMENT_RATE_2WKAVG'].unique()\narray(['(0.000)', '1', '0.666', ..., '0.779', '0.856', '0'], dtype=object)\narray(['0', '1', '0.666', ..., '0.879', '0.779', '0.856'], dtype=object)\n"

In [8]:
# replace the '(null)' within 'FULFILLMENT_RATE_2WKAVG' column values with '0'.
X['FULFILLMENT_RATE_2WKAVG'] = X['FULFILLMENT_RATE_2WKAVG'].str.replace('\(null\)', '0')

In [9]:
# check the unique values now
X['FULFILLMENT_RATE_2WKAVG'].unique()

array(['0', '1', '0.666', ..., '0.879', '0.779', '0.856'], dtype=object)

In [40]:
# convert string to decimal
# example
a = '0.856'
b = float(a)
print(a, b)

0.856 0.856

In [10]:
# convert all the string values within 'FULFILLMENT_RATE_2WKAVG' to decimal
X['FULFILLMENT_RATE_2WKAVG'] = X['FULFILLMENT_RATE_2WKAVG'].apply(lambda x: float(x))

In [11]:
# check the unique values now
X['FULFILLMENT_RATE_2WKAVG'].unique()

array([0.   , 1.   , 0.666, ..., 0.879, 0.779, 0.856])

In [12]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'FULFILLMENT_RATE_2WKAVG' is eliminated now

['CAL_DATE', 'VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG']

<b>Fixing 'CAL_DATE'</b>

In [13]:
# convert CAL_DATE to datetime type
X['CAL_DATE'] = pd.to_datetime(X['CAL_DATE'])

# from X, split the date column to individual columns and append them back to X
X = pd.DataFrame({
    # 'CAL_DATE': X['CAL_DATE'],
    'YEAR': X['CAL_DATE'].dt.year,
    'MONTH': X['CAL_DATE'].dt.month,
    'DAY': X['CAL_DATE'].dt.day,
    'DAY_OF_YEAR': X['CAL_DATE'].dt.dayofyear,
    'WEEK': X['CAL_DATE'].dt.week,
    'WEEK_OF_YEAR': X['CAL_DATE'].dt.weekofyear,
    'DAY_OF_WEEK': X['CAL_DATE'].dt.dayofweek,
    'WEEKDAY': X['CAL_DATE'].dt.weekday,
    'QUARTER': X['CAL_DATE'].dt.quarter
}).join(X)
# .join(X, lsuffix='_left')
# }).join(X, on='CAL_DATE', how='right', lsuffix='_left', rsuffix='_right')

# syntax example for join
# df_a.join(df_b, on='mukey', how='left', lsuffix='_left', rsuffix='_right')

# drop the original CAL_DATE column
# X_ext = X_ext.drop('CAL_DATE', axis='columns')

# reassign extended X back to X to overrite
# X = X_ext

In [14]:
X.head()

,DAY,DAY_OF_WEEK,DAY_OF_YEAR,MONTH,QUARTER,WEEK,WEEKDAY,WEEK_OF_YEAR,YEAR,CAL_DATE,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,6,0,310,11,4,45,0,45,2017,2017-11-06,...,4,0.333,0,2,196,1,-75.00,10.8333,0,0
1,24,1,114,4,2,17,1,17,2018,2018-04-24,...,5,0.000,0,7,107,9,800.00,4.3333,0,0
2,7,0,127,5,2,19,0,19,2018,2018-05-07,...,2,0.000,0,13,178,3,50.00,2.0000,0,0
3,18,2,291,10,4,42,2,42,2017,2017-10-18,...,2,0.000,0,12,166,5,0.00,2.5000,0,0
4,6,2,340,12,4,49,2,49,2017,2017-12-06,...,3,0.000,0,2,108,77,6.94,73.0000,15996,118

In [16]:
# drop the original CAL_DATE column
X = X.drop('CAL_DATE', axis='columns')

# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'CAL_DATE' is eliminated now

['VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG']

<b>Fixing 'OUTPROC_FLAG'</b>

In [17]:
# convert the boolean values True/False to integer 1/0
X['OUTPROC_FLAG']=X['OUTPROC_FLAG'].apply(lambda x: np.where(x==False,0,1))

In [18]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'OUTPROC_FLAG' is eliminated now

['VNDR_ID', 'ITEM_NO', 'CRFA_C']

<b>Fixing 'CRFA_C'</b>

In [19]:
# replace the null values within the column 'CRFA_C' with ASCII for '0' that is NUL.
X['CRFA_C'].fillna(chr(0), inplace=True)

# convert all the string values to ASCII equivalents
X['CRFA_C'] = X['CRFA_C'].apply(lambda x: ord(x))

In [20]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'CRFA_C' is eliminated now

['VNDR_ID', 'ITEM_NO']

<b>Fixing 'VNDR_ID'</b>

In [21]:
# check the unique values for 'VNDR_ID'
print(X['VNDR_ID'].unique())
print(len(X['VNDR_ID'].unique()))

['AD98' 'DN 4' 'Z582' 'T606' 'JK65' 'ASC3' 'B682' 'PYI' 'BW 6' 'Z975'
 'AYG' 'KBV2' 'PFE' 'CX83' 'HDR1' 'A587' 'CJ25' 'LA67' 'LF53' 'AW76'
 'DL37' 'RGT1' 'KD74' 'JX64' 'DO80' 'NEM' 'FK17' 'KF53' 'DDE1' 'KD02'
 'CA16' 'FI95' 'KC86' 'ET44' 'I536' 'Z984' 'SCP' 'LE75' 'PH M' 'G984'
 'CBT' 'CM 6' 'KA75' 'LF31' 'KT34' 'FS17' 'HUN' 'CHS' 'ALUA' 'KB21' 'ESC'
 'CM 2' 'ETN9' 'KU19' 'HX26' 'IMQ4' 'CC37' 'I075' 'JW10' 'T852' 'KF28'
 'RGT' 'PPU1' 'P664' 'KU17' 'FP10' 'AKR' 'FC35' 'AL53' 'LB05' 'CJ06'
 'BW 1' 'AO02' 'AE55' 'T785' 'DN23' 'TM' 'KJ92' 'CJ49' 'JER' 'KF79' 'T155'
 'KZ42' 'BW 7' 'X333' 'JW87' 'KG12' 'FWJ' 'LJ52' 'AA02' 'KB00' 'Z807'
 'GRK' 'CON' 'PMY' 'HF89' 'DDE5' 'Z157' 'IM46' 'KB36' 'GT G' 'FS22' 'ER53'
 'DVO' 'TBS' 'JW06' 'KQ71' 'BF20' 'KYS4' 'R609' 'TL 1' 'KB42' 'EQ24'
 'AKR1' 'CM 5' 'KD84' 'KR38' 'FLP1' 'CDB' 'CUM4' 'A867' 'AB57' 'JK42'
 'RWY' 'JS56' 'DAN2' 'LA89' 'H884' 'EU99' 'CM 4' 'EM32' 'LB26' 'EK79'
 'TL 2' 'SPD' 'JE68' 'KT06' 'HF60' 'LE23' 'L657' 'SIC' 'PTH' 'W656' 'PH K'
 'MZT1' 'KA49' 'KK24' 'S2I' 'GZ95' 'BY83' 'MUN' 'KH53' 'T481' 'Q672'
 'KO51' 'GZM' 'GX31' 'DG65' 'EK41' 'JS78' 'E929' 'JR93' 'HOR1' 'LB07'
 'JT10' 'LA93' 'JA50' 'HDR' 'KP72' 'C291' 'KY80' 'SMU' 'AY06' 'BF64' 'PHM'
 'CO92' 'KQ21' 'INS' 'CX98' 'GR88' 'JR97' 'KN40' 'BT27' 'PXU' 'CJ44'
 'JT27' 'H491' 'FAR4' 'HA63' 'BO39' 'KU98' 'WHT' 'IMM' 'JR94' 'EP45'
 'ETN3' 'GJ76' 'FQ15' 'T499' 'JS94' 'LG20' 'AN57' 'X284' 'II78' 'KJ64'
 'BOD' 'LA77' 'JP68' 'HA81' 'BU56' 'IZ97' 'N439' 'JR67' 'HOS' 'GRR2' 'EPC'
 'DN A' 'DUG' 'JT44' 'KD60' 'JT22' 'KM10' 'IQ79' 'BC93' 'LF49' 'KV79'
 'LH03' 'FOU' 'BTE' 'LF80' 'H725' 'MGM' 'AB55' 'KD64' 'KV68' 'KU73' 'KA66'
 'JT29' 'GU12' 'DANG' 'MFG' 'I263' 'KP33' 'A846' 'A446' 'LK23' 'KS01'
 'JU93' 'DG54' 'JO15' 'KV9P' 'JS67' 'T681' 'AY55' 'EQ87' 'PH T' 'DANT'
 'JN73' 'LB02' 'HE72' 'DU57' 'SLP' 'ZFA' 'BO83' 'KP32' 'JT39' 'JS84'
 'GUN1' 'V987' 'AK66' 'SRQ' 'ADG' 'JX89' 'II79' 'BLR' 'KQ35' 'JE91' 'JZ14'
 'ANJ' 'LG13' 'MYP' 'Z538' 'HN' 'SPR' 'IMQ1' 'FXF' 'GO39' 'KT94' 'DR'
 'KH73' 'FEI' 'P508' 'MWR' 'JI56' 'FK70' 'LA09' 'S095' 'CA49' 'OSM' 'ETE'
 'SOC' 'PH 8' 'AD53' 'JS19' 'JJ62' 'EQ19' 'CD10' 'STN' 'B707' 'JW08'
 'AA64' 'LI99' 'END' 'G088' 'DANC' 'KU18' 'KR76' 'BU54' 'KYS1' 'CP78'
 'J373' 'NTS' 'KS11' 'JT56' 'EM64' 'VIM1' 'LB76' 'BU53' 'FIP3' 'KO82'
 'MR 1' 'KG81' 'IS96' 'JL26' 'LJ61' 'LB39' 'KP73' 'AC97' 'R060' 'LH78'
 'KV95' 'KG20' 'KJ02' 'DZ32' 'JV33' 'P510' 'CI52' 'G923' 'G661' 'MZT4'
 'AQ 5' 'JX67' 'POL' 'SIR' 'CM 8' 'JM69' 'IY04' 'JS26' 'HE10' 'CV78'
 'AJ59' 'JE90' 'KM43' 'DF65' 'FSC' 'BTS' 'JR46' 'JR60' 'S679' 'MOE' 'W897'
 'LG69' 'WEM' 'Q102' 'GA64' 'ED02' 'GE44' 'DANK' 'DJ35' 'KYS2' 'JX85'
 'KK85' 'JN47' 'JW73' 'MCH6' 'CUM2' 'KN60' 'JD32' 'KA31' 'KRC' 'KN54'
 'Y481' 'HS49' 'JR17' 'M966' 'AF75' 'V560' 'W772' 'T047' 'P207' 'Z919'
 'EP86' 'MOT1' 'CHM' 'UMC' 'R813' 'AQ49' 'LB04' 'CM 1' 'JX10' 'HU78'
 'GR87' 'FON6' 'RDH' 'LD65' 'EQ32' 'JX26' 'L803' 'JX06' 'JJ05' 'S099'
 'FR88' 'T580' 'WMG' 'SXM' 'SKF' 'KJ03' 'FHP1' 'EF49' 'ENC' 'GRO2' 'DAN5'
 'KD05' 'JLK' 'ANZ' 'GE27' 'TPU' 'ATP' 'CM 9' 'W249' 'LB15' 'JU10' 'CO22'
 'GH86' 'DI30' 'KY05' 'JF69' 'EL30' 'JC16' 'DN 8' 'POL1' 'KY65' 'Y258'
 'LH47' 'JW34' 'SFR' 'LG63' 'JK41' 'AD75' 'JS41' 'LJ91' 'JJ44' 'B216'
 'JM86' 'GRR' 'EY27' 'F997' 'LSI6' 'JL75' 'GX40' 'B124' 'JU62' 'I463'
 'EO73' 'DDE4' 'GS68' 'EQ07' 'KQ77' 'KZ34' 'DF04' 'W792' 'GH70' 'KB84'
 'E925' 'CB36' 'JK62' 'DA03' 'MPE' 'I440' 'F046' 'M4D' 'AR93' 'P895'
 'LOR4' 'ED51' 'KC04' 'MW' 'C6F' 'HV45' 'HLL' 'AU37' 'LJ30' 'NMC' 'KZ35'
 'LF64' 'FU41' 'T945' 'EK60' 'LJ42' 'KL10' 'KZ89' 'JR56' 'JJ71' 'PQR'
 'JJ46' 'KK69' 'JJ33' 'KM98' 'AR99' 'E388' 'HW40' 'JA20' 'DB33' 'ARN'
 'KO28' 'ROKK' 'EJ07' 'JZ50' 'EH46' 'MGM2' 'JQ37' 'GR99' 'RCJ' 'AVG'
 'T912' 'JJ63' 'ROKN' 'CC51' 'IR18' 'B491' 'T383' 'CD58' 'V689' 'H758'
 'DG28' 'SPM' 'FL95' 'DM77' 'N562' 'V001' 'FO97' 'MCH5' 'DU71' 'LJ53'
 'D268' 'GC09' 'STM' 'KT15' 'GTR3' 'DD50' 'LI90' 'JP04' 'EJ44' 'LI37'
 'C680' 'IP45' 'IY79' 'PH 9' 'T547' 'W555' 'G099' 'KX78' 'JN60' 'R018'
 'Y979' 'LK33' 'JN63' 'JU96' 'DANU' 'AQ46' 'LJ31' 'DN' 'LJ41' 'NBC' 'LG43'
 'ED19' 'LJ94' 'JX40' 'IR41' 'LJ28' 'EE38' 'LC18' 'BG27' 'EGP1' 'EQ15'
 'IK15' 'DQ37' 'KB24' 'D463' 'JR62' 'W987' 'SLC' 'JW61' 'PPA' 'CHR2'
 'T851' 'JC37' 'BO86' 'GYRB' 'LB51' 'FM09' 'I375' 'A448' 'V069' 'LK05'
 'KO97' 'LHI' 'INM2' 'JX47' 'S988' 'FBH' 'MIU1' 'ID04' 'KI46' 'T519' 'ARB'
 'ROK3' 'CUM9' 'DH88' 'JX91' 'FJ96' 'IQ28' 'FA55' 'SPC' 'DR 5' 'FT80'
 'JH92' 'EG75' 'DL27' 'JKQ' 'CJ04' 'JQ46' 'LB79' 'FQ76' 'AKR2' 'H022'
 'GYR1' 'BU57' 'JJ32' 'KPT' 'KR52' 'EET' 'LK86' 'FN09' 'JT14' 'FU40' 'SAR'
 'I661' 'MMU' 'V165' 'JN30' 'DSC' 'JU00' 'AJ66' 'JQ52' 'EM45' 'Q796' 'EGW'
 'JH87' 'GKB' 'S535' 'GRR1' 'CY65' 'EK06' 'LK44' 'VKR1' 'KY62' 'KRU'
 'JG32' 'PDB1' 'TCO1' 'AI 1' 'DP14' 'MTQ1' 'NCD' 'RYC' 'HA89' 'HDN' 'KR86'
 'HDR8' 'AG43' 'LJ50' 'S804' 'ET68' 'R063' 'FA84' 'JT34' 'LJ54' 'FK53'
 'YTC1' 'IA89' 'CC50' 'BO88' 'DN F' 'CUM6' 'EP89' 'H316' 'DMI' 'AGV2'
 'LB59' 'ABC' 'GX15' 'PRE' 'WSO' 'AK91' 'EM77' 'G942' 'T898' 'K528' 'W684'
 'LJ26' 'ROK4' 'KN36' 'HZ67' 'ET87' 'A3M' 'K110' 'EI71' 'KO64' 'LH28'
 'DK02' 'KE42' 'AN44' 'T943' 'AE78' 'JS21' 'V312' 'B797' 'EJ08' 'AI56'
 'HTF' 'W928' 'GBF' 'DB01' 'NWU' 'JR01' 'AQP' 'PIW' 'EM56' 'VRT' 'ROK7'
 'BN75' 'BZ05' 'T878' 'Z931' 'LOR3' 'L965' 'KL37' 'AD49' 'AMP' 'EM10'
 'JO12' 'CAT1' 'Q082' 'V743' 'NPW' 'EM76' 'PAC1' 'V240' 'JQ50' 'EN90'
 'LDD' 'KV05' 'T759' 'V745' 'EK92' 'KN42' 'J364' 'ROK2' 'D172' 'DN 2'
 'AH86' 'ETN2' 'JC36' 'FK30' 'J566']
786

In [24]:
# converting VNDR_IDs to corresponding hashed number equivalents
# from hashlib import md5

# X['VNDR_ID'] = X['VNDR_ID'].apply(lambda x: md5(str(x).encode()).hexdigest(), 4)

# how hash() function works
'''
a = 'AYS5'
b = hash(a)
print(a, b)
'''

AYS5 -2235507493350117487

In [25]:
# converting VNDR_IDs to corresponding hashed number equivalents

X['VNDR_ID'] = X['VNDR_ID'].apply(lambda x: hash(x))

In [26]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'VNDR_ID' is eliminated now

['ITEM_NO']

<b>Fixing 'ITEM_NO'</b>

In [28]:
# applying the same strategy as 'VNDR_ID' to fix 'ITEM_NO'
X['ITEM_NO'] = X['ITEM_NO'].apply(lambda x: hash(x))

In [29]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'ITEM_NO' is eliminated now

[]

In [30]:
X.head()

,DAY,DAY_OF_WEEK,DAY_OF_YEAR,MONTH,QUARTER,WEEK,WEEKDAY,WEEK_OF_YEAR,YEAR,VNDR_ID,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,6,0,310,11,4,45,0,45,2017,-3298046730185830363,...,4,0.333,0,2,196,1,-75.00,10.8333,0,0
1,24,1,114,4,2,17,1,17,2018,-3298046730185830363,...,5,0.000,0,7,107,9,800.00,4.3333,0,0
2,7,0,127,5,2,19,0,19,2018,-8181519795740652654,...,2,0.000,0,13,178,3,50.00,2.0000,0,0
3,18,2,291,10,4,42,2,42,2017,335569075441642136,...,2,0.000,0,12,166,5,0.00,2.5000,0,0
4,6,2,340,12,4,49,2,49,2017,612886189846981134,...,3,0.000,0,2,108,77,6.94,73.0000,15996,118

# Eliminating issues with Skew and Scaling

<b>Eliminating Skew via log conversion</b>

In [31]:
# the code converts the numeric features values to log equivalents and also takes care of the negative values
X = X.apply(lambda x: ((1+x)/(1+abs(x)))*(np.log(1 + abs(x))))

In [33]:
X.head(20)

,DAY,DAY_OF_WEEK,DAY_OF_YEAR,MONTH,QUARTER,WEEK,WEEKDAY,WEEK_OF_YEAR,YEAR,VNDR_ID,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,1.945910,0.000000,5.739793,2.484907,1.609438,3.828641,0.000000,3.828641,7.609862,-42.639862,...,1.609438,0.287432,0.000000,1.098612,5.283204,0.693147,-4.216767,2.470918,0.000000,0.000000
1,3.218876,0.693147,4.744932,1.609438,1.098612,2.890372,0.693147,2.890372,7.610358,-42.639862,...,1.791759,0.000000,0.000000,2.079442,4.682131,2.302585,6.685861,1.673970,0.000000,0.000000
2,2.079442,0.000000,4.852030,1.791759,1.098612,2.995732,0.000000,2.995732,7.610358,-43.548410,...,1.098612,0.000000,0.000000,2.639057,5.187386,1.386294,3.931826,1.098612,0.000000,0.000000
3,2.944439,1.098612,5.676754,2.397895,1.609438,3.761200,1.098612,3.761200,7.609862,40.354604,...,1.098612,0.000000,0.000000,2.564949,5.117994,1.791759,0.000000,1.252763,0.000000,0.000000
4,1.945910,1.098612,5.831882,2.564949,1.609438,3.912023,1.098612,3.912023,7.609862,40.956956,...,1.386294,0.000000,0.000000,1.098612,4.691348,4.356709,2.071913,4.304065,9.680156,4.779123
5,2.995732,0.000000,3.931826,1.098612,0.693147,2.197225,0.000000,2.197225,7.610358,42.070184,...,1.098612,0.000000,0.000000,2.564949,5.081404,2.890372,-3.949189,3.888412,0.000000,5.568345
6,2.833213,0.000000,4.672829,1.609438,1.098612,2.833213,0.000000,2.833213,7.610358,-40.288595,...,2.397895,0.000000,0.693147,2.484907,3.332205,4.043051,-3.105381,4.080357,7.979339,6.306275
7,3.091042,1.098612,5.153292,1.945910,1.098612,3.258097,1.098612,3.258097,7.609862,-40.288595,...,2.484907,0.223144,0.693147,2.484907,0.693147,3.828641,3.620601,4.019380,8.920255,5.616771
8,2.639057,0.000000,5.762051,2.484907,1.609438,3.850148,0.000000,3.850148,7.609862,42.272791,...,0.000000,0.000000,0.000000,2.079442,4.709530,1.609438,4.615121,1.466329,5.817111,0.000000
9,3.218876,1.098612,4.976734,1.791759,1.098612,3.091042,1.098612,3.091042,7.609862,42.482504,...,0.693147,0.000000,0.000000,2.772589,3.218876,0.000000,0.000000,0.000000,0.000000,0.000000
10,2.890372,0.693147,5.673323,2.397895,1.609438,3.761200,0.693147,3.761200,7.609862,-42.590353,...,2.944439,0.000000,0.000000,1.945910,4.406719,3.988984,4.427836,3.881564,7.250636,6.484635
11,3.178054,1.609438,4.418841,1.386294,0.693147,2.564949,1.609438,2.564949,7.610358,39.483359,...,1.386294,0.287432,0.000000,1.791759,4.406719,3.332205,0.000000,3.460513,9.764513,8.321178
12,1.098612,1.098612,4.812184,1.791759,1.098612,2.944439,1.098612,2.944439,7.610358,-43.475486,...,1.791759,0.000000,0.000000,2.484907,3.433987,3.044522,4.416549,2.662586,5.918894,4.828314
13,3.258097,0.693147,5.332719,2.079442,1.386294,3.433987,0.693147,3.433987,7.609862,43.017494,...,0.000000,0.000000,0.000000,1.945910,5.347108,2.302585,-4.259378,2.674149,6.891626,0.000000
14,3.135494,1.386294,4.406719,1.386294,0.693147,2.564949,1.386294,2.564949,7.610358,43.663849,...,1.791759,0.000000,0.000000,2.079442,4.406719,3.465736,-3.869849,3.753416,0.000000,0.000000
15,0.693147,1.609438,5.817111,2.564949,1.609438,3.891820,1.609438,3.891820,7.609862,41.939687,...,3.555348,0.405465,0.000000,0.693147,4.744932,2.995732,4.510860,2.813407,6.236370,0.000000
16,1.098612,1.098612,5.370638,2.197225,1.386294,3.465736,1.098612,3.465736,7.609862,41.638659,...,1.386294,0.000000,0.000000,1.098612,4.744932,2.484907,-3.258106,2.525729,6.520621,0.000000
17,2.995732,1.609438,2.995732,0.693147,0.693147,1.386294,1.609438,1.386294,7.610358,-42.897473,...,0.000000,0.000000,0.000000,1.945910,4.744932,2.079442,-3.212440,2.412927,0.000000,0.000000
18,2.079442,0.000000,4.852030,1.791759,1.098612,2.995732,0.000000,2.995732,7.610358,-41.292434,...,1.945910,0.000000,0.693147,0.000000,5.187386,2.302585,5.860786,1.540431,0.000000,4.454347
19,2.484907,1.386294,2.484907,0.693147,0.693147,1.098612,1.386294,1.098612,7.610358,-42.590353,...,0.000000,0.000000,0.000000,2.197225,4.663439,2.302585,-3.532422,3.120892,4.672829,0.000000

<b>Eliminating Scaling issues using RobustScaler</b>

In [34]:
# Again, scaling only applies to numerical data.
from sklearn.preprocessing import RobustScaler

# initializing the scaler object
scaler = RobustScaler()

# define a new dataframe to hold the scaled numeric features
X_scaled = pd.DataFrame(data = X)

# apply the scaling and populate the data
X_scaled = scaler.fit_transform(X)

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [35]:
print(X_scaled)

[[-1.01351785 -1.26185951  0.61067518 ... -0.12729816 -0.62828234
   0.        ]
 [ 0.44052113 -0.63092975 -0.4354716  ... -0.48882726 -0.62828234
   0.        ]
 [-0.86099226 -1.26185951 -0.32285246 ... -0.74983398 -0.62828234
   0.        ]
 ...
 [ 0.68623108 -0.63092975 -1.81399696 ... -0.70204252 -0.62828234
   0.        ]
 [-0.22177378 -0.63092975 -0.91337278 ...  0.86157981  0.89250165
   1.65014801]
 [ 0.72249588 -0.63092975  0.59018977 ... -0.83254276 -0.62828234
   0.        ]]

In [38]:
colm_list = ['CAL_DATE',
 'VNDR_ID',
 'ITEM_NO',
 'LOC',
 'SR_FLAG',
 'CRFA_C',
 'CRFA_R',
 'CRFA_F',
 'CRFA_A',
 'EOQ',
 'PKG_QTY',
 'OUTPROC_FLAG',
 'SCORE_EDI_INSTABILITY_AVG',
 'ORDER_EDI_INSTABILITY_POSITIVE_ONLY_AVG',
 'FULFILLMENT_RATE_2WKAVG',
 'SPEC_CNG_ELEM',
 'SPEC_CNG_FPE',
 'SPEC_CNG_MRP',
 'SPEC_CNG_OH_ADJ',
 'SPEC_CNG_PCTS',
 'SPEC_CNG_PEG',
 'SPEC_CNG_POR_ASN',
 'SPEC_CNG_POTR',
 'SPEC_CNG_SCHED',
 'SPEC_CNG_UNKNWN',
 'DROPIN',
 'PAST_DUES',
 'CUR_INTRN_DAYS',
 'MDL_BLD_RATE',
 'PREV_MNTH_RECORD_COUNT',
 'PREV_MNTH_PERCENT',
 'AVG_SIX_MNTH_CNT',
 'SHRT_PPM',
 'QA_PPM']
X = pd.DataFrame(X_scaled, columns=colm_list)

ValueError: Shape of passed values is (41, 5049841), indices imply (34, 5049841)

In [37]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,-1.013518,-1.26186,0.610675,0.777608,1.77566,0.640362,-1.26186,0.640362,0.0,-0.038284,...,0.160964,0.287432,0.0,-0.703752,0.190533,-0.824986,-0.578167,-0.127298,-0.628282,0.000000
1,0.440521,-0.63093,-0.435472,-0.485427,0.00000,-0.412723,-0.63093,-0.412723,1.0,-0.038284,...,0.292481,0.000000,0.0,0.110909,0.065200,-0.166015,0.916708,-0.488827,-0.628282,0.000000
2,-0.860992,-1.26186,-0.322852,-0.222392,0.00000,-0.294469,-1.26186,-0.294469,1.0,-0.048862,...,-0.207519,0.000000,0.0,0.575717,0.170553,-0.541183,0.539098,-0.749834,-0.628282,0.000000
3,0.127047,-0.26186,0.544386,0.652077,1.77566,0.564668,-0.26186,0.564668,0.0,0.928028,...,-0.207519,0.000000,0.0,0.514164,0.156084,-0.375168,0.000000,-0.679905,-0.628282,0.000000
4,-1.013518,-0.26186,0.707512,0.893085,1.77566,0.733947,-0.26186,0.733947,0.0,0.935041,...,0.000000,0.000000,0.0,-0.703752,0.067121,0.675030,0.284083,0.704295,0.751854,0.854222