In [1]:
# import the required libraries
import pandas as pd

# data = pd.read_csv('//home//anshul//anaconda3//anshul//scikit-learn//Datasets//DTML_Master.csv', chunksize=10240)
# data = pd.read_csv('//home//anshul//anaconda3//anshul//scikit-learn//Datasets//DTML_Master.csv')
data = pd.read_csv('//home//anshul//anaconda3//anshul//scikit-learn//Datasets//DTML_Master.csv', nrows=10240)

In [2]:
print(type(data))
print(data.shape)
print(data.head())

# df = pd.DataFrame(data)

<class 'pandas.core.frame.DataFrame'>
(10240, 34)
     CAL_DATE VNDR_ID        ITEM_NO  LOC SR_FLAG CRFA_C  CRFA_R  CRFA_F  \
0  2017-11-06    AD98  A22-72740-000   13       N      S       9       1
1  2018-04-24    AD98  A22-69882-000   34       N      S       9       1
2  2018-05-07    DN 4   DN EPG150230   65       N      S       9       1
3  2017-10-18    Z582   04-31885-200   65       N      S       9       1
4  2017-12-06    T606   12-20828-000   34       Y      S       9       1

   CRFA_A  EOQ   ...    SPEC_CNG_UNKNWN DROPIN  PAST_DUES  CUR_INTRN_DAYS  \
0       2    1   ...                  4  0.333          0               2
1       2    0   ...                  5  0.000          0               7
2       2    1   ...                  2  0.000          0              13
3       2    1   ...                  2  0.000          0              12
4       2    5   ...                  3  0.000          0               2

  MDL_BLD_RATE  PREV_MNTH_RECORD_COUNT  PREV_MNTH_PERCENT  AVG_SIX_MNTH_CNT  \
0          196                       1             -75.00           10.8333
1          107                       9             800.00            4.3333
2          178                       3              50.00            2.0000
3          166                       5               0.00            2.5000
4          108                      77               6.94           73.0000

   SHRT_PPM  QA_PPM
0         0       0
1         0       0
2         0       0
3         0       0
4     15996     118

[5 rows x 34 columns]

In [3]:
# split the data into feature matrix (X) and response vector (y)
X = data.drop('SR_FLAG', axis='columns')
y = data['SR_FLAG']

In [4]:
X.head()
# y.head()

,CAL_DATE,VNDR_ID,ITEM_NO,LOC,CRFA_C,CRFA_R,CRFA_F,CRFA_A,EOQ,PKG_QTY,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,2017-11-06,AD98,A22-72740-000,13,S,9,1,2,1,44,...,4,0.333,0,2,196,1,-75.00,10.8333,0,0
1,2018-04-24,AD98,A22-69882-000,34,S,9,1,2,0,48,...,5,0.000,0,7,107,9,800.00,4.3333,0,0
2,2018-05-07,DN 4,DN EPG150230,65,S,9,1,2,1,12,...,2,0.000,0,13,178,3,50.00,2.0000,0,0
3,2017-10-18,Z582,04-31885-200,65,S,9,1,2,1,20,...,2,0.000,0,12,166,5,0.00,2.5000,0,0
4,2017-12-06,T606,12-20828-000,34,S,9,1,2,5,50,...,3,0.000,0,2,108,77,6.94,73.0000,15996,118

In [5]:
import numpy as np

# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)

In [6]:
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

['CAL_DATE', 'VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG', 'FULFILLMENT_RATE_2WKAVG']

<b>Fixing 'FULFILLMENT_RATE_2WKAVG'</b>

In [7]:
X['FULFILLMENT_RATE_2WKAVG'].head()

0    (null)
1    (null)
2         1
3    (null)
4     0.666
Name: FULFILLMENT_RATE_2WKAVG, dtype: object

In [36]:
# identify the unique/distinct set of values for 'FULFILLMENT_RATE_2WKAVG'
# X.groupby('FULFILLMENT_RATE_2WKAVG').nunique()
# len(X['FULFILLMENT_RATE_2WKAVG'].unique()) -- 1002
# 'FULFILLMENT_RATE_2WKAVG' contains deciman numbers along with a null.
# eliminating the nulls from a copy of X
'''
X_mod = X
X_nonnum = X_mod.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)
# modify 'FULFILLMENT_RATE_2WKAVG' to replace NULLS with zeros
X_mod['FULFILLMENT_RATE_2WKAVG'].fillna(0.0, inplace=True)
# checin the non numeric columns again
X_nnumcols = list(X_nonnum)
print(X_nnumcols)
['CAL_DATE', 'VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG', 'FULFILLMENT_RATE_2WKAVG']
X_mod['FULFILLMENT_RATE_2WKAVG'] = X_mod['FULFILLMENT_RATE_2WKAVG'].str.replace('\(0\)', '0')
X_mod['FULFILLMENT_RATE_2WKAVG'].unique()
array(['(0.000)', '1', '0.666', ..., '0.779', '0.856', '0'], dtype=object)
array(['0', '1', '0.666', ..., '0.879', '0.779', '0.856'], dtype=object)
'''

"\nX_mod = X\nX_nonnum = X_mod.select_dtypes(exclude=np.number)\nX_nnumcols = list(X_nonnum)\nprint(X_nnumcols)\n# modify 'FULFILLMENT_RATE_2WKAVG' to replace NULLS with zeros\nX_mod['FULFILLMENT_RATE_2WKAVG'].fillna(0.0, inplace=True)\n# checin the non numeric columns again\nX_nnumcols = list(X_nonnum)\nprint(X_nnumcols)\n['CAL_DATE', 'VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG', 'FULFILLMENT_RATE_2WKAVG']\nX_mod['FULFILLMENT_RATE_2WKAVG'] = X_mod['FULFILLMENT_RATE_2WKAVG'].str.replace('\\(0\\)', '0')\nX_mod['FULFILLMENT_RATE_2WKAVG'].unique()\narray(['(0.000)', '1', '0.666', ..., '0.779', '0.856', '0'], dtype=object)\narray(['0', '1', '0.666', ..., '0.879', '0.779', '0.856'], dtype=object)\n"

In [8]:
# replace the '(null)' within 'FULFILLMENT_RATE_2WKAVG' column values with '0'.
X['FULFILLMENT_RATE_2WKAVG'] = X['FULFILLMENT_RATE_2WKAVG'].str.replace('\(null\)', '0')

In [9]:
# check the unique values now
X['FULFILLMENT_RATE_2WKAVG'].unique()

array(['0', '1', '0.666', '0.5', '0.333', '0.155', '0.254', '0.875',
       '0.377', '0.438', '0.576', '0.25', '0.988', '0.517', '0.842',
       '0.142', '0.28', '0.175', '0.313', '0.59', '0.297', '0.185', '0.2',
       '0.546', '0.311', '0.253', '0.833', '0.732', '0.687', '0.381',
       '0.327', '0.16', '0.714', '0.211', '0.165', '0.19', '0.212', '0.6',
       '0.093', '0.891', '0.478', '0.277', '0.409', '0.909', '0.722',
       '0.868', '0.222', '0.528', '0.269', '0.1', '0.439', '0.276',
       '0.416', '0.214', '0.4', '0.178', '0.555', '0.916', '0.24',
       '0.551', '0.146', '0.845', '0.179', '0.791', '0.638', '0.121',
       '0.166', '0.337', '0.125', '0.892', '0.675', '0.41', '0.466',
       '0.295', '0.933', '0.167', '0.375', '0.32', '0.111', '0.285',
       '0.357', '0.571', '0.524', '0.129', '0.588', '0.961', '0.958',
       '0.322', '0.857', '0.397', '0.176', '0.384', '0.656', '0.427',
       '0.882', '0.668', '0.3', '0.152', '0.948', '0.629', '0.617',
       '0.766', '0.703', '0.437', '0.367', '0.9', '0.97', '0.993', '0.55',
       '0.213', '0.363', '0.497', '0.316', '0.827', '0.547', '0.724',
       '0.457', '0.56', '0.47', '0.518', '0.18', '0.358', '0.709',
       '0.371', '0.537', '0.604', '0.557', '0.653', '0.087', '0.188',
       '0.134', '0.456', '0.122', '0.63', '0.592', '0.076', '0.227',
       '0.8', '0.7', '0.52', '0.931', '0.229', '0.731', '0.039', '0.552',
       '0.578', '0.914', '0.77', '0.869', '0.119', '0.866', '0.392',
       '0.663', '0.98', '0.294', '0.454', '0.181', '0.159', '0.266',
       '0.315', '0.428', '0.366', '0.288', '0.365', '0.305', '0.915',
       '0.364', '0.475', '0.038', '0.243', '0.228', '0.692', '0.785',
       '0.636', '0.264', '0.62', '0.192', '0.284', '0.149', '0.473',
       '0.289', '0.756', '0.218', '0.154', '0.685', '0.059', '0.498',
       '0.624', '0.487', '0.816', '0.103', '0.903', '0.374', '0.846',
       '0.818', '0.605', '0.348', '0.474', '0.749', '0.96', '0.533',
       '0.553', '0.028', '0.282', '0.863', '0.272', '0.205', '0.508',
       '0.828', '0.538', '0.094', '0.443', '0.872', '0.062', '0.545',
       '0.21', '0.326', '0.75', '0.937', '0.31', '0.291', '0.928',
       '0.434', '0.966', '0.986', '0.923', '0.461', '0.065', '0.66',
       '0.48', '0.655', '0.329', '0.529', '0.298', '0.976', '0.033',
       '0.959', '0.657', '0.156', '0.865', '0.328', '0.543', '0.055',
       '0.249', '0.49', '0.183', '0.926', '0.029', '0.862', '0.85',
       '0.989', '0.42', '0.678', '0.429', '0.226', '0.342', '0.332',
       '0.231', '0.589', '0.255', '0.594', '0.131', '0.071', '0.172',
       '0.615', '0.256', '0.34', '0.823', '0.479', '0.777', '0.067',
       '0.198', '0.521', '0.969', '0.544', '0.752', '0.527', '0.612',
       '0.851', '0.372', '0.611', '0.699', '0.187', '0.763', '0.929',
       '0.081', '0.905', '0.436', '0.274', '0.572', '0.031', '0.33',
       '0.401', '0.534', '0.74', '0.021', '0.136', '0.747', '0.353',
       '0.843', '0.126', '0.088', '0.235', '0.768', '0.477', '0.884',
       '0.411', '0.782', '0.035', '0.531', '0.195', '0.153', '0.736',
       '0.525', '0.679', '0.718', '0.368', '0.883', '0.558', '0.789',
       '0.895', '0.259', '0.258', '0.603', '0.402', '0.972', '0.887',
       '0.577', '0.238', '0.077', '0.13', '0.516', '0.04', '0.645',
       '0.102', '0.568', '0.335', '0.711', '0.194', '0.994', '0.967',
       '0.608', '0.783', '0.965', '0.596', '0.665', '0.186', '0.769',
       '0.025', '0.265', '0.133', '0.95', '0.113', '0.593', '0.951',
       '0.278', '0.085', '0.964', '0.444', '0.237', '0.492', '0.369',
       '0.83', '0.15', '0.422', '0.772', '0.705', '0.648', '0.513',
       '0.913', '0.745', '0.744', '0.625', '0.681', '0.407', '0.735',
       '0.066', '0.043', '0.425', '0.852', '0.07', '0.248', '0.35',
       '0.581', '0.14', '0.26', '0.609', '0.647', '0.819', '0.449',
       '0.619', '0.84', '0.307', '0.896', '0.987', '0.245', '0.888',
       '0.137', '0.115', '0.622', '0.509', '0.008', '0.135', '0.207',
       '0.523', '0.995', '0.027', '0.083', '0.468', '0.193', '0.73',
       '0.922', '0.403', '0.981', '0.82', '0.476', '0.984', '0.985',
       '0.871', '0.695', '0.947', '0.114', '0.607', '0.767', '0.232',
       '0.396', '0.092', '0.921', '0.707', '0.727', '0.962', '0.275',
       '0.485', '0.02', '0.559', '0.803', '0.54', '0.794', '0.729',
       '0.859', '0.346', '0.344', '0.054', '0.911', '0.09', '0.414',
       '0.567', '0.089', '0.68', '0.885', '0.263', '0.362', '0.296',
       '0.53', '0.383', '0.388', '0.672', '0.463', '0.583', '0.997',
       '0.825', '0.634', '0.405', '0.801', '0.549', '0.386', '0.433',
       '0.574', '0.633', '0.674', '0.378', '0.421', '0.323', '0.446',
       '0.053', '0.484', '0.345', '0.379', '0.977', '0.314', '0.445',
       '0.812', '0.548', '0.811', '0.912', '0.535', '0.061', '0.281',
       '0.448', '0.643', '0.944', '0.566', '0.853', '0.821', '0.216',
       '0.462', '0.158', '0.441', '0.642', '0.935', '0.393', '0.719',
       '0.435', '0.496', '0.45', '0.99', '0.952', '0.127', '0.488',
       '0.941', '0.971', '0.495', '0.725', '0.225', '0.098', '0.251',
       '0.844', '0.704', '0.349', '0.689', '0.063', '0.787', '0.788',
       '0.257', '0.459', '0.419', '0.338', '0.673', '0.032', '0.874',
       '0.512', '0.541', '0.242', '0.246', '0.542', '0.044', '0.244',
       '0.565', '0.036', '0.65', '0.831', '0.209', '0.118', '0.312',
       '0.712', '0.684', '0.169', '0.12', '0.016', '0.733', '0.412',
       '0.807', '0.017', '0.304', '0.861', '0.792', '0.708', '0.413',
       '0.471', '0.72', '0.942', '0.746', '0.626', '0.658', '0.601',
       '0.876', '0.221', '0.197', '0.38', '0.639', '0.481', '0.682',
       '0.761', '0.415', '0.837', '0.491', '0.432', '0.677', '0.515',
       '0.688', '0.123', '0.215', '0.051', '0.834', '0.306', '0.472',
       '0.641', '0.742', '0.426', '0.376', '0.738', '0.424', '0.71',
       '0.447', '0.398', '0.469', '0.713', '0.771', '0.877', '0.356',
       '0.813', '0.303', '0.112', '0.482', '0.998', '0.917', '0.81',
       '0.683', '0.148', '0.694', '0.686', '0.616', '0.108', '0.08',
       '0.564', '0.562', '0.804', '0.786', '0.219', '0.056', '0.667',
       '0.069', '0.734', '0.784', '0.982', '0.489', '0.317', '0.584',
       '0.532', '0.217', '0.097', '0.423', '0.268', '0.105', '0.775',
       '0.141', '0.569', '0.755', '0.321', '0.318', '0.072', '0.262',
       '0.586', '0.208', '0.252', '0.455', '0.271', '0.57', '0.664',
       '0.702', '0.646', '0.758', '0.001', '0.754', '0.143', '0.464',
       '0.395', '0.308', '0.241', '0.261', '0.661', '0.881', '0.057',
       '0.417', '0.753', '0.382', '0.161', '0.385', '0.331', '0.324',
       '0.826', '0.236', '0.925', '0.79', '0.954', '0.091', '0.561',
       '0.023', '0.203', '0.949', '0.019', '0.506', '0.92', '0.924',
       '0.757', '0.973', '0.204', '0.809', '0.273', '0.037', '0.171',
       '0.23', '0.361', '0.759', '0.442', '0.406', '0.22', '0.015',
       '0.957', '0.139', '0.793', '0.189', '0.045', '0.347', '0.94',
       '0.354', '0.452', '0.806', '0.591', '0.239', '0.292', '0.764',
       '0.343', '0.595', '0.451', '0.64', '0.465', '0.996', '0.526',
       '0.999', '0.099', '0.511', '0.096', '0.776', '0.223', '0.36'],
      dtype=object)

In [11]:
# convert string to decimal
# example
a = '0.856'
b = float(a)
print(a, b)

0.856 0.856

In [10]:
# convert all the string values within 'FULFILLMENT_RATE_2WKAVG' to decimal
X['FULFILLMENT_RATE_2WKAVG'] = X['FULFILLMENT_RATE_2WKAVG'].apply(lambda x: float(x))

In [11]:
# check the unique values now
X['FULFILLMENT_RATE_2WKAVG'].unique()

array([0.   , 1.   , 0.666, 0.5  , 0.333, 0.155, 0.254, 0.875, 0.377,
       0.438, 0.576, 0.25 , 0.988, 0.517, 0.842, 0.142, 0.28 , 0.175,
       0.313, 0.59 , 0.297, 0.185, 0.2  , 0.546, 0.311, 0.253, 0.833,
       0.732, 0.687, 0.381, 0.327, 0.16 , 0.714, 0.211, 0.165, 0.19 ,
       0.212, 0.6  , 0.093, 0.891, 0.478, 0.277, 0.409, 0.909, 0.722,
       0.868, 0.222, 0.528, 0.269, 0.1  , 0.439, 0.276, 0.416, 0.214,
       0.4  , 0.178, 0.555, 0.916, 0.24 , 0.551, 0.146, 0.845, 0.179,
       0.791, 0.638, 0.121, 0.166, 0.337, 0.125, 0.892, 0.675, 0.41 ,
       0.466, 0.295, 0.933, 0.167, 0.375, 0.32 , 0.111, 0.285, 0.357,
       0.571, 0.524, 0.129, 0.588, 0.961, 0.958, 0.322, 0.857, 0.397,
       0.176, 0.384, 0.656, 0.427, 0.882, 0.668, 0.3  , 0.152, 0.948,
       0.629, 0.617, 0.766, 0.703, 0.437, 0.367, 0.9  , 0.97 , 0.993,
       0.55 , 0.213, 0.363, 0.497, 0.316, 0.827, 0.547, 0.724, 0.457,
       0.56 , 0.47 , 0.518, 0.18 , 0.358, 0.709, 0.371, 0.537, 0.604,
       0.557, 0.653, 0.087, 0.188, 0.134, 0.456, 0.122, 0.63 , 0.592,
       0.076, 0.227, 0.8  , 0.7  , 0.52 , 0.931, 0.229, 0.731, 0.039,
       0.552, 0.578, 0.914, 0.77 , 0.869, 0.119, 0.866, 0.392, 0.663,
       0.98 , 0.294, 0.454, 0.181, 0.159, 0.266, 0.315, 0.428, 0.366,
       0.288, 0.365, 0.305, 0.915, 0.364, 0.475, 0.038, 0.243, 0.228,
       0.692, 0.785, 0.636, 0.264, 0.62 , 0.192, 0.284, 0.149, 0.473,
       0.289, 0.756, 0.218, 0.154, 0.685, 0.059, 0.498, 0.624, 0.487,
       0.816, 0.103, 0.903, 0.374, 0.846, 0.818, 0.605, 0.348, 0.474,
       0.749, 0.96 , 0.533, 0.553, 0.028, 0.282, 0.863, 0.272, 0.205,
       0.508, 0.828, 0.538, 0.094, 0.443, 0.872, 0.062, 0.545, 0.21 ,
       0.326, 0.75 , 0.937, 0.31 , 0.291, 0.928, 0.434, 0.966, 0.986,
       0.923, 0.461, 0.065, 0.66 , 0.48 , 0.655, 0.329, 0.529, 0.298,
       0.976, 0.033, 0.959, 0.657, 0.156, 0.865, 0.328, 0.543, 0.055,
       0.249, 0.49 , 0.183, 0.926, 0.029, 0.862, 0.85 , 0.989, 0.42 ,
       0.678, 0.429, 0.226, 0.342, 0.332, 0.231, 0.589, 0.255, 0.594,
       0.131, 0.071, 0.172, 0.615, 0.256, 0.34 , 0.823, 0.479, 0.777,
       0.067, 0.198, 0.521, 0.969, 0.544, 0.752, 0.527, 0.612, 0.851,
       0.372, 0.611, 0.699, 0.187, 0.763, 0.929, 0.081, 0.905, 0.436,
       0.274, 0.572, 0.031, 0.33 , 0.401, 0.534, 0.74 , 0.021, 0.136,
       0.747, 0.353, 0.843, 0.126, 0.088, 0.235, 0.768, 0.477, 0.884,
       0.411, 0.782, 0.035, 0.531, 0.195, 0.153, 0.736, 0.525, 0.679,
       0.718, 0.368, 0.883, 0.558, 0.789, 0.895, 0.259, 0.258, 0.603,
       0.402, 0.972, 0.887, 0.577, 0.238, 0.077, 0.13 , 0.516, 0.04 ,
       0.645, 0.102, 0.568, 0.335, 0.711, 0.194, 0.994, 0.967, 0.608,
       0.783, 0.965, 0.596, 0.665, 0.186, 0.769, 0.025, 0.265, 0.133,
       0.95 , 0.113, 0.593, 0.951, 0.278, 0.085, 0.964, 0.444, 0.237,
       0.492, 0.369, 0.83 , 0.15 , 0.422, 0.772, 0.705, 0.648, 0.513,
       0.913, 0.745, 0.744, 0.625, 0.681, 0.407, 0.735, 0.066, 0.043,
       0.425, 0.852, 0.07 , 0.248, 0.35 , 0.581, 0.14 , 0.26 , 0.609,
       0.647, 0.819, 0.449, 0.619, 0.84 , 0.307, 0.896, 0.987, 0.245,
       0.888, 0.137, 0.115, 0.622, 0.509, 0.008, 0.135, 0.207, 0.523,
       0.995, 0.027, 0.083, 0.468, 0.193, 0.73 , 0.922, 0.403, 0.981,
       0.82 , 0.476, 0.984, 0.985, 0.871, 0.695, 0.947, 0.114, 0.607,
       0.767, 0.232, 0.396, 0.092, 0.921, 0.707, 0.727, 0.962, 0.275,
       0.485, 0.02 , 0.559, 0.803, 0.54 , 0.794, 0.729, 0.859, 0.346,
       0.344, 0.054, 0.911, 0.09 , 0.414, 0.567, 0.089, 0.68 , 0.885,
       0.263, 0.362, 0.296, 0.53 , 0.383, 0.388, 0.672, 0.463, 0.583,
       0.997, 0.825, 0.634, 0.405, 0.801, 0.549, 0.386, 0.433, 0.574,
       0.633, 0.674, 0.378, 0.421, 0.323, 0.446, 0.053, 0.484, 0.345,
       0.379, 0.977, 0.314, 0.445, 0.812, 0.548, 0.811, 0.912, 0.535,
       0.061, 0.281, 0.448, 0.643, 0.944, 0.566, 0.853, 0.821, 0.216,
       0.462, 0.158, 0.441, 0.642, 0.935, 0.393, 0.719, 0.435, 0.496,
       0.45 , 0.99 , 0.952, 0.127, 0.488, 0.941, 0.971, 0.495, 0.725,
       0.225, 0.098, 0.251, 0.844, 0.704, 0.349, 0.689, 0.063, 0.787,
       0.788, 0.257, 0.459, 0.419, 0.338, 0.673, 0.032, 0.874, 0.512,
       0.541, 0.242, 0.246, 0.542, 0.044, 0.244, 0.565, 0.036, 0.65 ,
       0.831, 0.209, 0.118, 0.312, 0.712, 0.684, 0.169, 0.12 , 0.016,
       0.733, 0.412, 0.807, 0.017, 0.304, 0.861, 0.792, 0.708, 0.413,
       0.471, 0.72 , 0.942, 0.746, 0.626, 0.658, 0.601, 0.876, 0.221,
       0.197, 0.38 , 0.639, 0.481, 0.682, 0.761, 0.415, 0.837, 0.491,
       0.432, 0.677, 0.515, 0.688, 0.123, 0.215, 0.051, 0.834, 0.306,
       0.472, 0.641, 0.742, 0.426, 0.376, 0.738, 0.424, 0.71 , 0.447,
       0.398, 0.469, 0.713, 0.771, 0.877, 0.356, 0.813, 0.303, 0.112,
       0.482, 0.998, 0.917, 0.81 , 0.683, 0.148, 0.694, 0.686, 0.616,
       0.108, 0.08 , 0.564, 0.562, 0.804, 0.786, 0.219, 0.056, 0.667,
       0.069, 0.734, 0.784, 0.982, 0.489, 0.317, 0.584, 0.532, 0.217,
       0.097, 0.423, 0.268, 0.105, 0.775, 0.141, 0.569, 0.755, 0.321,
       0.318, 0.072, 0.262, 0.586, 0.208, 0.252, 0.455, 0.271, 0.57 ,
       0.664, 0.702, 0.646, 0.758, 0.001, 0.754, 0.143, 0.464, 0.395,
       0.308, 0.241, 0.261, 0.661, 0.881, 0.057, 0.417, 0.753, 0.382,
       0.161, 0.385, 0.331, 0.324, 0.826, 0.236, 0.925, 0.79 , 0.954,
       0.091, 0.561, 0.023, 0.203, 0.949, 0.019, 0.506, 0.92 , 0.924,
       0.757, 0.973, 0.204, 0.809, 0.273, 0.037, 0.171, 0.23 , 0.361,
       0.759, 0.442, 0.406, 0.22 , 0.015, 0.957, 0.139, 0.793, 0.189,
       0.045, 0.347, 0.94 , 0.354, 0.452, 0.806, 0.591, 0.239, 0.292,
       0.764, 0.343, 0.595, 0.451, 0.64 , 0.465, 0.996, 0.526, 0.999,
       0.099, 0.511, 0.096, 0.776, 0.223, 0.36 ])

In [12]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'FULFILLMENT_RATE_2WKAVG' is eliminated now

['CAL_DATE', 'VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG']

<b>Fixing 'CAL_DATE'</b>

In [13]:
# convert CAL_DATE to datetime type
X['CAL_DATE'] = pd.to_datetime(X['CAL_DATE'])

# from X, split the date column to individual columns and append them back to X
X = pd.DataFrame({
    # 'CAL_DATE': X['CAL_DATE'],
    'YEAR': X['CAL_DATE'].dt.year,
    'MONTH': X['CAL_DATE'].dt.month,
    'DAY': X['CAL_DATE'].dt.day,
    'DAY_OF_YEAR': X['CAL_DATE'].dt.dayofyear,
    'WEEK': X['CAL_DATE'].dt.week,
    'WEEK_OF_YEAR': X['CAL_DATE'].dt.weekofyear,
    'DAY_OF_WEEK': X['CAL_DATE'].dt.dayofweek,
    'WEEKDAY': X['CAL_DATE'].dt.weekday,
    'QUARTER': X['CAL_DATE'].dt.quarter
}).join(X)
# .join(X, lsuffix='_left')
# }).join(X, on='CAL_DATE', how='right', lsuffix='_left', rsuffix='_right')

# syntax example for join
# df_a.join(df_b, on='mukey', how='left', lsuffix='_left', rsuffix='_right')

# drop the original CAL_DATE column
# X_ext = X_ext.drop('CAL_DATE', axis='columns')

# reassign extended X back to X to overrite
# X = X_ext

In [14]:
X.head()

,YEAR,MONTH,DAY,DAY_OF_YEAR,WEEK,WEEK_OF_YEAR,DAY_OF_WEEK,WEEKDAY,QUARTER,CAL_DATE,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,2017,11,6,310,45,45,0,0,4,2017-11-06,...,4,0.333,0,2,196,1,-75.00,10.8333,0,0
1,2018,4,24,114,17,17,1,1,2,2018-04-24,...,5,0.000,0,7,107,9,800.00,4.3333,0,0
2,2018,5,7,127,19,19,0,0,2,2018-05-07,...,2,0.000,0,13,178,3,50.00,2.0000,0,0
3,2017,10,18,291,42,42,2,2,4,2017-10-18,...,2,0.000,0,12,166,5,0.00,2.5000,0,0
4,2017,12,6,340,49,49,2,2,4,2017-12-06,...,3,0.000,0,2,108,77,6.94,73.0000,15996,118

In [15]:
# drop the original CAL_DATE column
X = X.drop('CAL_DATE', axis='columns')

# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'CAL_DATE' is eliminated now

['VNDR_ID', 'ITEM_NO', 'CRFA_C', 'OUTPROC_FLAG']

<b>Fixing 'OUTPROC_FLAG'</b>

In [16]:
# convert the boolean values True/False to integer 1/0
X['OUTPROC_FLAG']=X['OUTPROC_FLAG'].apply(lambda x: np.where(x==False,0,1))

In [17]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'OUTPROC_FLAG' is eliminated now

['VNDR_ID', 'ITEM_NO', 'CRFA_C']

<b>Fixing 'CRFA_C'</b>

In [18]:
# replace the null values within the column 'CRFA_C' with ASCII for '0' that is NUL.
X['CRFA_C'].fillna(chr(0), inplace=True)

# convert all the string values to ASCII equivalents
X['CRFA_C'] = X['CRFA_C'].apply(lambda x: ord(x))

In [19]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'CRFA_C' is eliminated now

['VNDR_ID', 'ITEM_NO']

<b>Fixing 'VNDR_ID'</b>

In [20]:
# check the unique values for 'VNDR_ID'
# print(X['VNDR_ID'].unique())
print(len(X['VNDR_ID'].unique()))

548

In [24]:
# converting VNDR_IDs to corresponding hashed number equivalents
# from hashlib import md5

# X['VNDR_ID'] = X['VNDR_ID'].apply(lambda x: md5(str(x).encode()).hexdigest(), 4)

# how hash() function works
'''
a = 'AYS5'
b = hash(a)
print(a, b)
'''

AYS5 -2235507493350117487

In [21]:
# converting VNDR_IDs to corresponding hashed number equivalents

X['VNDR_ID'] = X['VNDR_ID'].apply(lambda x: hash(x))

In [22]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'VNDR_ID' is eliminated now

['ITEM_NO']

<b>Fixing 'ITEM_NO'</b>

In [23]:
# applying the same strategy as 'VNDR_ID' to fix 'ITEM_NO'
X['ITEM_NO'] = X['ITEM_NO'].apply(lambda x: hash(x))

In [24]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

# 'ITEM_NO' is eliminated now

[]

In [25]:
X.head()

,YEAR,MONTH,DAY,DAY_OF_YEAR,WEEK,WEEK_OF_YEAR,DAY_OF_WEEK,WEEKDAY,QUARTER,VNDR_ID,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,2017,11,6,310,45,45,0,0,4,-3913108969903261015,...,4,0.333,0,2,196,1,-75.00,10.8333,0,0
1,2018,4,24,114,17,17,1,1,2,-3913108969903261015,...,5,0.000,0,7,107,9,800.00,4.3333,0,0
2,2018,5,7,127,19,19,0,0,2,7440659487853874633,...,2,0.000,0,13,178,3,50.00,2.0000,0,0
3,2017,10,18,291,42,42,2,2,4,-3659268744774451009,...,2,0.000,0,12,166,5,0.00,2.5000,0,0
4,2017,12,6,340,49,49,2,2,4,-2272046932557479946,...,3,0.000,0,2,108,77,6.94,73.0000,15996,118

# Eliminating issues with Skew and Scaling

<b>Eliminating Skew via log conversion</b>

In [26]:
# the code converts the numeric features values to log equivalents and also takes care of the negative values
X = X.apply(lambda x: ((1+x)/(1+abs(x)))*(np.log(1 + abs(x))))

In [27]:
X.head(20)

,YEAR,MONTH,DAY,DAY_OF_YEAR,WEEK,WEEK_OF_YEAR,DAY_OF_WEEK,WEEKDAY,QUARTER,VNDR_ID,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,7.609862,2.484907,1.945910,5.739793,3.828641,3.828641,0.000000,0.000000,1.609438,-42.810864,...,1.609438,0.287432,0.000000,1.098612,5.283204,0.693147,-4.216767,2.470918,0.000000,0.000000
1,7.610358,1.609438,3.218876,4.744932,2.890372,2.890372,0.693147,0.693147,1.098612,-42.810864,...,1.791759,0.000000,0.000000,2.079442,4.682131,2.302585,6.685861,1.673970,0.000000,0.000000
2,7.610358,1.791759,2.079442,4.852030,2.995732,2.995732,0.000000,0.000000,1.098612,43.453491,...,1.098612,0.000000,0.000000,2.639057,5.187386,1.386294,3.931826,1.098612,0.000000,0.000000
3,7.609862,2.397895,2.944439,5.676754,3.761200,3.761200,1.098612,1.098612,1.609438,-42.743795,...,1.098612,0.000000,0.000000,2.564949,5.117994,1.791759,0.000000,1.252763,0.000000,0.000000
4,7.609862,2.564949,1.945910,5.831882,3.912023,3.912023,1.098612,1.098612,1.609438,-42.267213,...,1.386294,0.000000,0.000000,1.098612,4.691348,4.356709,2.071913,4.304065,9.680156,4.779123
5,7.610358,1.098612,2.995732,3.931826,2.197225,2.197225,0.000000,0.000000,0.693147,-43.331332,...,1.098612,0.000000,0.000000,2.564949,5.081404,2.890372,-3.949189,3.888412,0.000000,5.568345
6,7.610358,1.609438,2.833213,4.672829,2.833213,2.833213,0.000000,0.000000,1.098612,42.911246,...,2.397895,0.000000,0.693147,2.484907,3.332205,4.043051,-3.105381,4.080357,7.979339,6.306275
7,7.609862,1.945910,3.091042,5.153292,3.258097,3.258097,1.098612,1.098612,1.098612,42.911246,...,2.484907,0.223144,0.693147,2.484907,0.693147,3.828641,3.620601,4.019380,8.920255,5.616771
8,7.609862,2.484907,2.639057,5.762051,3.850148,3.850148,0.000000,0.000000,1.609438,42.790464,...,0.000000,0.000000,0.000000,2.079442,4.709530,1.609438,4.615121,1.466329,5.817111,0.000000
9,7.609862,1.791759,3.218876,4.976734,3.091042,3.091042,1.098612,1.098612,1.098612,-43.555642,...,0.693147,0.000000,0.000000,2.772589,3.218876,0.000000,0.000000,0.000000,0.000000,0.000000
10,7.609862,2.397895,2.890372,5.673323,3.761200,3.761200,0.693147,0.693147,1.609438,-43.572645,...,2.944439,0.000000,0.000000,1.945910,4.406719,3.988984,4.427836,3.881564,7.250636,6.484635
11,7.610358,1.386294,3.178054,4.418841,2.564949,2.564949,1.609438,1.609438,0.693147,39.732554,...,1.386294,0.287432,0.000000,1.791759,4.406719,3.332205,0.000000,3.460513,9.764513,8.321178
12,7.610358,1.791759,1.098612,4.812184,2.944439,2.944439,1.098612,1.098612,1.098612,-43.014517,...,1.791759,0.000000,0.000000,2.484907,3.433987,3.044522,4.416549,2.662586,5.918894,4.828314
13,7.609862,2.079442,3.258097,5.332719,3.433987,3.433987,0.693147,0.693147,1.386294,-43.116734,...,0.000000,0.000000,0.000000,1.945910,5.347108,2.302585,-4.259378,2.674149,6.891626,0.000000
14,7.610358,1.386294,3.135494,4.406719,2.564949,2.564949,1.386294,1.386294,0.693147,-43.591209,...,1.791759,0.000000,0.000000,2.079442,4.406719,3.465736,-3.869849,3.753416,0.000000,0.000000
15,7.609862,2.564949,0.693147,5.817111,3.891820,3.891820,1.609438,1.609438,1.609438,40.895161,...,3.555348,0.405465,0.000000,0.693147,4.744932,2.995732,4.510860,2.813407,6.236370,0.000000
16,7.609862,2.197225,1.098612,5.370638,3.465736,3.465736,1.098612,1.098612,1.386294,43.014846,...,1.386294,0.000000,0.000000,1.098612,4.744932,2.484907,-3.258106,2.525729,6.520621,0.000000
17,7.610358,0.693147,2.995732,2.995732,1.386294,1.386294,1.609438,1.609438,0.693147,42.577485,...,0.000000,0.000000,0.000000,1.945910,4.744932,2.079442,-3.212440,2.412927,0.000000,0.000000
18,7.610358,1.791759,2.079442,4.852030,2.995732,2.995732,0.000000,0.000000,1.098612,43.135844,...,1.945910,0.000000,0.693147,0.000000,5.187386,2.302585,5.860786,1.540431,0.000000,4.454347
19,7.610358,0.693147,2.484907,2.484907,1.098612,1.098612,1.386294,1.386294,0.693147,-43.572645,...,0.000000,0.000000,0.000000,2.197225,4.663439,2.302585,-3.532422,3.120892,4.672829,0.000000

<b>Eliminating Scaling issues using RobustScaler</b>

In [28]:
# Again, scaling only applies to numerical data.
from sklearn.preprocessing import RobustScaler

# initializing the scaler object
scaler = RobustScaler()

# define a new dataframe to hold the scaled numeric features
X_scaled = pd.DataFrame(data = X)

# apply the scaling and populate the data
X_scaled = scaler.fit_transform(X)

In [29]:
print(X_scaled)

[[ 0.          0.77760758 -1.01351785 ... -0.1923584  -0.67887321
   0.        ]
 [ 1.         -0.48542683  0.44052113 ... -0.54997742 -0.67887321
   0.        ]
 [ 1.         -0.22239242 -0.86099226 ... -0.80816124 -0.67887321
   0.        ]
 ...
 [ 1.         -1.22239242  0.         ... -0.53616626  0.55223104
   0.        ]
 [ 0.          0.19264508 -1.01351785 ...  0.38314504  0.23900646
   0.94854867]
 [ 0.          0.19264508  0.56997029 ... -0.04317934 -0.22991013
   1.25830867]]

In [30]:
colm_list = ['DAY',
 'DAY_OF_WEEK',
 'DAY_OF_YEAR',
 'MONTH',
 'QUARTER',
 'WEEK',
 'WEEKDAY',
 'WEEK_OF_YEAR',
 'YEAR',
 'VNDR_ID',
 'ITEM_NO',
 'LOC',
 'CRFA_C',
 'CRFA_R',
 'CRFA_F',
 'CRFA_A',
 'EOQ',
 'PKG_QTY',
 'OUTPROC_FLAG',
 'SCORE_EDI_INSTABILITY_AVG',
 'ORDER_EDI_INSTABILITY_POSITIVE_ONLY_AVG',
 'FULFILLMENT_RATE_2WKAVG',
 'SPEC_CNG_ELEM',
 'SPEC_CNG_FPE',
 'SPEC_CNG_MRP',
 'SPEC_CNG_OH_ADJ',
 'SPEC_CNG_PCTS',
 'SPEC_CNG_PEG',
 'SPEC_CNG_POR_ASN',
 'SPEC_CNG_POTR',
 'SPEC_CNG_SCHED',
 'SPEC_CNG_UNKNWN',
 'DROPIN',
 'PAST_DUES',
 'CUR_INTRN_DAYS',
 'MDL_BLD_RATE',
 'PREV_MNTH_RECORD_COUNT',
 'PREV_MNTH_PERCENT',
 'AVG_SIX_MNTH_CNT',
 'SHRT_PPM',
 'QA_PPM']
X = pd.DataFrame(X_scaled, columns=colm_list)

In [31]:
X.head()

,DAY,DAY_OF_WEEK,DAY_OF_YEAR,MONTH,QUARTER,WEEK,WEEKDAY,WEEK_OF_YEAR,YEAR,VNDR_ID,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,0.0,0.777608,-1.013518,0.695758,0.727358,0.727358,-1.584963,-1.584963,1.77566,-0.967092,...,0.000000,0.287432,0.0,-0.630930,0.713400,-0.916314,-0.578832,-0.192358,-0.678873,0.000000
1,1.0,-0.485427,0.440521,-0.406785,-0.391856,-0.391856,-0.584963,-0.584963,0.00000,-0.967092,...,0.106949,0.000000,0.0,0.261860,-0.083233,-0.245126,0.917762,-0.549977,-0.678873,0.000000
2,1.0,-0.222392,-0.860992,-0.288095,-0.266177,-0.266177,-1.584963,-1.584963,0.00000,0.036849,...,-0.299649,0.000000,0.0,0.771244,0.586407,-0.627249,0.539718,-0.808161,-0.678873,0.000000
3,0.0,0.652077,0.127047,0.625896,0.646911,0.646911,0.000000,0.000000,1.77566,-0.966311,...,-0.299649,0.000000,0.0,0.703788,0.494438,-0.458157,0.000000,-0.738988,-0.678873,0.000000
4,0.0,0.893085,-1.013518,0.797815,0.826820,0.826820,0.000000,0.000000,1.77566,-0.960765,...,-0.130895,0.000000,0.0,-0.630930,-0.071018,0.611510,0.284410,0.630241,0.639770,0.836307

In [27]:
# get the list of all the non-numeric columns
X_nonnum = X.select_dtypes(exclude=np.number)
X_nnumcols = list(X_nonnum)
print(X_nnumcols)

[]

In [28]:
X.head()

,DAY,DAY_OF_WEEK,DAY_OF_YEAR,MONTH,QUARTER,WEEK,WEEKDAY,WEEK_OF_YEAR,YEAR,VNDR_ID,...,SPEC_CNG_UNKNWN,DROPIN,PAST_DUES,CUR_INTRN_DAYS,MDL_BLD_RATE,PREV_MNTH_RECORD_COUNT,PREV_MNTH_PERCENT,AVG_SIX_MNTH_CNT,SHRT_PPM,QA_PPM
0,-1.013518,-1.26186,0.610675,0.777608,1.77566,0.640362,-1.26186,0.640362,0.0,-0.036082,...,0.160964,0.287432,0.0,-0.703752,0.190533,-0.824986,-0.578167,-0.127298,-0.628282,0.000000
1,0.440521,-0.63093,-0.435472,-0.485427,0.00000,-0.412723,-0.63093,-0.412723,1.0,-0.036082,...,0.292481,0.000000,0.0,0.110909,0.065200,-0.166015,0.916708,-0.488827,-0.628282,0.000000
2,-0.860992,-1.26186,-0.322852,-0.222392,0.00000,-0.294469,-1.26186,-0.294469,1.0,0.958976,...,-0.207519,0.000000,0.0,0.575717,0.170553,-0.541183,0.539098,-0.749834,-0.628282,0.000000
3,0.127047,-0.26186,0.544386,0.652077,1.77566,0.564668,-0.26186,0.564668,0.0,0.956535,...,-0.207519,0.000000,0.0,0.514164,0.156084,-0.375168,0.000000,-0.679905,-0.628282,0.000000
4,-1.013518,-0.26186,0.707512,0.893085,1.77566,0.733947,-0.26186,0.733947,0.0,0.961523,...,0.000000,0.000000,0.0,-0.703752,0.067121,0.675030,0.284083,0.704295,0.751854,0.854222

# Implementing models on the engineered dataset

- Logistic Regression

In [32]:
# split the scaled dataset into a training and testing set
from sklearn.model_selection import train_test_split

# splitting the data into groups of 75/25 as train/test ratio with a fixed random state of 0.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [33]:
# check the types of the records
print('X_train Type: ', type(X_train))
print('X_test Type: ', type(X_test))
print('y_train Type: ', type(y_train))
print('y_test Type: ', type(y_test))

# check the shapes of the records
print('X_train Shape: ', X_train.shape)
print('X_test Shape: ', X_test.shape)
print('y_train Shape: ', y_train.shape)
print('y_test Shape: ', y_test.shape)

X_train Type:  <class 'pandas.core.frame.DataFrame'>
X_test Type:  <class 'pandas.core.frame.DataFrame'>
y_train Type:  <class 'pandas.core.series.Series'>
y_test Type:  <class 'pandas.core.series.Series'>
X_train Shape:  (7680, 41)
X_test Shape:  (2560, 41)
y_train Shape:  (7680,)
y_test Shape:  (2560,)

In [34]:
# Using LabelBinarizer to convert y_train and y_test to a binary array
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
y_trbin = lb.fit_transform(y_train)
y_tsbin = lb.fit_transform(y_test)
print('y_trbin Type: ', type(y_trbin))
print('y_tsbin Type: ', type(y_tsbin))

# convert the numpy array back to the pandas series
y_trbin = pd.Series(y_trbin.reshape(-1))
y_tsbin = pd.Series(y_tsbin.reshape(-1))
print('y_trbin Type: ', type(y_trbin))
print('y_trbin Shape: ', y_trbin.shape)
print('y_tsbin Type: ', type(y_tsbin))
print('y_tsbin Shape: ', y_tsbin.shape)

y_trbin Type:  <class 'numpy.ndarray'>
y_tsbin Type:  <class 'numpy.ndarray'>
y_trbin Type:  <class 'pandas.core.series.Series'>
y_trbin Shape:  (7680,)
y_tsbin Type:  <class 'pandas.core.series.Series'>
y_tsbin Shape:  (2560,)

In [36]:
print(y_trbin.head())
print(y_tsbin.head())

0    1
1    0
2    0
3    0
4    0
dtype: int64
0    0
1    0
2    0
3    1
4    1
dtype: int64

In [37]:
# Calculating the naive parameters for the data
# Pre-calculating the metrices for a naive model. 
# That is when the outcome is always predicted as true, how will the raw model behave.
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, matthews_corrcoef, classification_report

# predicting everything as True(Y)
y_naive = [1]*len(y_test)

print('Accuracy: ', accuracy_score(y_naive, y_tsbin))
print('Recall: ', recall_score(y_naive, y_tsbin))
print('Precision: ', precision_score(y_naive, y_tsbin))
print('F1-Score: ', f1_score(y_naive, y_tsbin))
# print('Matthews Correlation Coefficient: ', matthews_corrcoef(y_naive, y_test))
print('Classification Report: \n', classification_report(y_naive, y_tsbin, target_names=['Short'], labels=[1]))
# print ("Naive Predictor: [Accuracy score: {:.4f}, F-score: {:.4f}]".format(accuracy, fscore))

Accuracy:  0.28125
Recall:  0.28125
Precision:  1.0
F1-Score:  0.43902439024390244
Classification Report:
              precision    recall  f1-score   support

      Short       1.00      0.28      0.44      2560

avg / total       1.00      0.28      0.44      2560

In [40]:
## GridSearchCV is throwing a MemoryError ##
## GridSearchCV is throwing a MemoryError ##
## GridSearchCV is throwing a MemoryError ##
## GridSearchCV is throwing a MemoryError ##
## GridSearchCV is throwing a MemoryError ##

'''

# import all the required libraries/functions
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model.logistic import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score, fbeta_score
# from sklearn.metrics import make_scorer


# clf = LogisticRegression()

## GridSearchCV is throwing a MemoryError ##

# attributes for GridSearchCV
pipeline = Pipeline([    
    ('clf', LogisticRegression())
])

parameters = {
    'clf__penalty': ('l1', 'l2'),
    'clf__C': (0.01, 0.1, 1, 10),    
}

grid_search = GridSearchCV(pipeline, parameters, n_jobs=-1, verbose=1, scoring='accuracy', cv=3)

grid_search.fit(X_train, y_train)

# parameters for the attribute 'param_grid' ## BALCK BOX ##
# parameters = {'C': [10**-i for i in range(-5, 5)], 'class_weight': [None, 'balanced']}
# parameters = {'C': [10], 'class_weight': [None, 'balanced']}
# parameters = {'C': [10]}
# scorer for the attribute 'scoring' ## BALCK BOX ##
# scorer = make_scorer(fbeta_score, beta=0.5)

# create an object for GridSearchCV
# grid_obj = GridSearchCV(estimator=clf, param_grid=parameters, scoring=scorer)

# fitting the training dataset
# grid_fit = grid_obj.fit(X_train, y_train)

# get the best estimator
# best_clf = grid_fit.best_estimator_
'''

"\n\n# import all the required libraries/functions\nimport pandas as pd\nfrom sklearn.preprocessing import LabelEncoder\nfrom sklearn.linear_model.logistic import LogisticRegression\nfrom sklearn.model_selection import GridSearchCV\nfrom sklearn.pipeline import Pipeline\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import precision_score, recall_score, accuracy_score, fbeta_score\n# from sklearn.metrics import make_scorer\n\n\n# clf = LogisticRegression()\n\n## GridSearchCV is throwing a MemoryError ##\n\n# attributes for GridSearchCV\npipeline = Pipeline([    \n    ('clf', LogisticRegression())\n])\n\nparameters = {\n    'clf__penalty': ('l1', 'l2'),\n    'clf__C': (0.01, 0.1, 1, 10),    \n}\n\ngrid_search = GridSearchCV(pipeline, parameters, n_jobs=-1, verbose=1, scoring='accuracy', cv=3)\n\ngrid_search.fit(X_train, y_train)\n\n# parameters for the attribute 'param_grid' ## BALCK BOX ##\n# parameters = {'C': [10**-i for i in range(-5, 5)], 'class_weight': [None, 'balanced']}\n# parameters = {'C': [10], 'class_weight': [None, 'balanced']}\n# parameters = {'C': [10]}\n# scorer for the attribute 'scoring' ## BALCK BOX ##\n# scorer = make_scorer(fbeta_score, beta=0.5)\n\n# create an object for GridSearchCV\n# grid_obj = GridSearchCV(estimator=clf, param_grid=parameters, scoring=scorer)\n\n# fitting the training dataset\n# grid_fit = grid_obj.fit(X_train, y_train)\n\n# get the best estimator\n# best_clf = grid_fit.best_estimator_\n"

In [ ]:
# implementing Logistic Regression to the dataset
from sklearn.linear_model.logistic import LogisticRegression
from sklearn.metrics import precision_score, recall_score, accuracy_score, fbeta_score

clf = LogisticRegression()
clf.fit(X_train, y_trbin)
y_pred = clf.predict(X_test)